### ISSUE TITLE
Working with array of strings

### ISSUE THREAD

**Issue by unkleara** [IneoO/vue-multi-select#1]
Hi, I was wondering if using an array with just string values is possible with the multi-select. Looking at the examples and briefly in the source code this doesn't seem possible? If not, any interest in adding it?
 
Example:

```
data: [{
        name: 'first group',
        list: [
        "Alabama",
        "Alaska",
        "American Samoa",
        "Arizona",
        "Arkansas",
        "California",
        "Colorado",
        "Connecticut",
        "Delaware"
      ]
}]
```

**Comment by IneoO** [comment]
Hi,

It's actualy not possible.
But if you are interessed about having this feature, i can do it, I think, it'should be simple to implement it.

**Comment by IneoO** [comment]
Ok it's now possible with the new version 3.2.0, i made an exemple https://vue-multi-select.tuturu.io/#a_multiselect_array 

If you encounter any problems, let me know.
