### ISSUE TITLE
selectionChanged function implemented after component creat

### ISSUE THREAD

**Issue by guoqingpingls** [IneoO/vue-multi-select#11]
<multi-select
    class='select-insurance'
     @selectionChanged="updateValues"
     :options="options"
     :selectOptions="insuranceList" />
I have a trouble with function selectionChanged，I want to set some default choosed Items to this list ；
I  do that , before creat , I use updateValues(valueArray) to set some default choosed Items, but not as I wish， I got none;  in debugger I found the function updateValues will implement after created  why? and how can i realize my wish

**Comment by IneoO** [comment]
Hi,
I'm not sure tout understand your problem, 
Wish type of value did you pass ? Array of strings or array of objects ? If you pass array of objet toi only need to pass an attributs selected un the object like un thé example https://vue-multi-select.tuturu.io/#custom_multi_select instead or use disabled set selected, you Can change the name of attr with options.labelSElected

**Comment by guoqingpingls** [comment]
![image](https://user-images.githubusercontent.com/29391699/41084467-e43493e8-6a66-11e8-8eda-ff524f26cd97.png)


for example, there is a component we named it componentA, componentA is a modal and it used vue-multi-select, and there is a componentB, while we click a button of componentB, componentA will show;
now I have a demand that first I click the button in componentB, the componentA show , I choose lili, lucy, Tom,   click sure , to submit this choose, and then I click the same button to show componentA, I can get the people (lili lucy Tom) I have choosed last way , but I donnot konw how to make vue-multi-select to choosed those people as while as the componentA show.   did you know what I want？？

**Comment by IneoO** [comment]
Ok that need à feature, i will work on it tout night.

**Comment by IneoO** [comment]
Ok it's not possible with 3.4.0. You need use v-model instead of function with event, it should simplify everything for you. I made an example if you want to see how to use selected element 
https://vue-multi-select.tuturu.io/#a_multiselect_array

If you see any bug or have any question fell free to ask.
