### ISSUE TITLE
Displaying the selected item in the button

### ISSUE THREAD

**Issue by dormadekhin-denis** [IneoO/vue-multi-select#12]
Can I display the selected item in the button? In the parameters, you can specify label, but it would be more convenient to display the selected element

**Comment by IneoO** [comment]
Hi,
Actualy, it's note possible because it's not à tag input. It's maybe possible to do that. I will make possible to change the label button with à Watcher this we. I Can try to had this feature too. Or maybe à label who can bé change IS enough for you ?

**Comment by dormadekhin-denis** [comment]
I can offer my solution:
if the multiple attribute on a <select> input is false then display the currently selected item, or the default label, if the item is not selected
For this I transferred the function getBtnLabel in "computed":
```
 computed:{
    getBtnLabel: function () {
        return this.multi ? `${this.btnLabel} (${this.valueSelected.length})` :
                                    (this.valueSelected.length) ? this.valueSelected[this.valueSelected.length - 1][this.labelName]
                                    :this.btnLabel;
       },
    }
```

**Comment by dormadekhin-denis** [comment]
I can offer my solution:
Display the current selection of the selected item only if the select multiple = false
For this, I transferred the GetButLabel to computed property
```
 computed:{
	        getBtnLabel: function () {
		        return this.multi ? `${this.btnLabel} (${this.valueSelected.length})` :
                    (this.valueSelected.length) ? this.valueSelected[this.valueSelected.length - 1][this.labelName]
                    :this.btnLabel;
	        },
        },
```

**Comment by dormadekhin-denis** [comment]
@IneoO, from VueJS documentation

> Don’t use arrow functions on an options property or callback, such as created: () => console.log(this.a) or vm.$watch('a', newValue => this.myMethod()). Since arrow functions are bound to the parent context, this will not be the Vue instance as you’d expect, often resulting in errors such as Uncaught TypeError: Cannot read property of undefined or Uncaught TypeError: this.myMethod is not a function.

as far as I understand, this also applies to the calculated properties

**Comment by dormadekhin-denis** [comment]
oh I'm sorry) I did not even notice this

**Comment by IneoO** [comment]
Ok i have done it, (eslin says to not use nested ternary https://eslint.org/docs/rules/no-nested-ternary so i used if, else if)

And i changed the btnlabel into a prop.

Thx for your contribution.
