### ISSUE TITLE
Css not imported correctly

### ISSUE THREAD

**Issue by jjf21** [IneoO/vue-multi-select#14]
I'm not able to load component correctly,
I'm using MaterializeCss, and vue2, any idea where this is coming from?

![capture d ecran 2018-06-20 a 14 56 21](https://user-images.githubusercontent.com/29787388/41659648-2a5ace2c-749a-11e8-9975-ae537165cae8.png)

I've set the component like this 
`import multiSelect from 'vue-multi-select';
import 'vue-multi-select/dist/lib/vue-multi-select.min.css';
Vue.component('multi-select', multiSelect)`

Thanks for your help!

**Comment by IneoO** [comment]
Hi,
wish material lib did you use ?
i used 
```
"materialize-css": "^0.100.2",
"vue-multi-select": "^3.5.1"
```
Set lib like this
```
import multiSelect from 'vue-multi-select';
import 'materialize-css/dist/css/materialize.css';
import 'materialize-css/dist/js/materialize';
import 'vue-multi-select/dist/lib/vue-multi-select.min.css';
import App from './App';

Vue.config.productionTip = false;
Vue.component('multi-select', multiSelect);
```` 
and get this result 

![capture](https://user-images.githubusercontent.com/8982189/41663096-f215f088-74a2-11e8-8150-25d28475786a.PNG)

**Comment by IneoO** [comment]
@mracila25 can you provide a simple example ?

i made a repo with sass and vue multi select and all working fine

[https://github.com/IneoO/vue-multi-select-sass-test](https://github.com/IneoO/vue-multi-select-sass-test)

**Comment by mracila25** [comment]
What doing "Vue.config.productionTip = false;" ?

**Comment by IneoO** [comment]
I just used the vue init webpack and add sass. 

It just to prevent some team when you are not in production ([https://vuejs.org/v2/api/#productionTip](https://vuejs.org/v2/api/#productionTip))

**Comment by mracila25** [comment]
Ok, thank you so much!
