### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by ClemEtu** [IneoO/vue-multi-select#15]
Hello,
Is it possible to delete the search bar? Or, in the worst case, put the placeholder in French?

Thanks for your help :)

**Comment by IneoO** [comment]
Ok i will make a release to add these functions tomorrow.

thx !

**Comment by ClemEtu** [comment]
Thanks for this feature ! 

Have a good day :)

**Comment by IneoO** [comment]
It's now possible with 3.6.1
