### ISSUE TITLE
How can I apply customized template?

### ISSUE THREAD

**Issue by Jung-Younghun** [IneoO/vue-multi-select#18]
I wanna customize format of selected field and list field.
Can I use some options to apply template customized format with data value?
For example that I think(below),

selected field...
```
selectedFieldTemplate: function(dataItem){
    return dataItem.value + '(count: ' + dataItem.count + ')';
}
```

list item field...
In case of multi-select, I want to add checkbox in each item field.
```
listItemTemplate: function(dataItem){
    return '<input type="checkbox"/>' + dataItem.lable + '~' + dataItem.value;
}
```

**Comment by IneoO** [comment]
Hi,

For the first point you want this function only apply when element is selected ?

for the second point you prefer to see a checkbox instead of ✓ ?

**Comment by Jung-Younghun** [comment]
Hi,
Not only when element is selected, I mean some functions to customize template of each items in title and popup of Combobox. Is there any API to do this?

**Comment by IneoO** [comment]
for the first point yeah it should be possibble, i will make this feeature before the end of the week.

For the second point, not it's not possible, because i didn't split the component in two component and i don't use <slot></slot>

**Comment by Jung-Younghun** [comment]
Thanks,

if the first point should be possible, It's enough to use your component in my case.
Thanks for your help!!

**Comment by IneoO** [comment]
Take care, if you want to alter the option from outside of the multi-select for the you will need to manual reload multi-select. Options are deep copied for isolation.
