### ISSUE TITLE
Can not click again item in Firefox

### ISSUE THREAD

**Issue by TranChiNam** [IneoO/vue-multi-select#21]
Hi! 
Thks for issue in ipad before. Now, my tester has a bug in Firefox for me. 
When I click again an item in list options in Firefox has an error appear: "event is not defined"
![image](https://user-images.githubusercontent.com/22738182/43444996-66e5ac22-94cf-11e8-9143-535111c35686.png)
Hope you fix it soon! I am looking forward to hearing from you!

**Comment by IneoO** [comment]
Looks like the pb come from nuxt on firefox. I will dig on that. Thx

**Comment by IneoO** [comment]
So i created a repo with nuxt. It's working

https://github.com/IneoO/nuxt-vue-multi-select-test

I tested with firefox 61. (61.0.1) is not available on gentoo atm

Can u provide a repo with the pb ? or test with my repo if it's work ?

**Comment by TranChiNam** [comment]
Humh! I can't pb my repo. I will find the way to resolve it. Thks

**Comment by IneoO** [comment]
Ok don't hesite to ask for help or make a pr

**Comment by TranChiNam** [comment]
I found my issue!
I have 2 multi-select. (call: multi-1 and multi-2)
when I select item in multi-1 then I get v-model was selected on multi-1 push to :options in multi-2
Problem was happend when I unselect the last item in multi-1.
These codes were edited from pj in your repo. This just occured on FireFox. It is running normally on Chrome, IE 11 and other devices (mobile tablet) 
![Uploading image.png…]()

**Comment by IneoO** [comment]
Ok it was a pb with the unbind. should be fixed with the 3.7.1

**Comment by TranChiNam** [comment]
Yeb! Thks man 👍
