### ISSUE TITLE
Multiselect deselect all event

### ISSUE THREAD

**Issue by DragosPeta** [IneoO/vue-multi-select#23]
Greetings,

I needed on an application to have a button that resets my filters. Since i didn't had an event on vue-multi-select that deselects all the options, i had to clear the model, make a ref on it and call:

> this.$refs['vue-multi-select'].selectCurrent({ selectAll: true, func: function () { return true } })

I tried to use the deselect function from the component through the ref which has a typo: "deselctAll()" but it generated label bugs.

Wanted just to notice this and ask for an event that selects/deselects all in future.

I like this component a lot, good job!

**Comment by IneoO** [comment]
Hi thx,

It should be possible.

You have to clear data in the model and use the manual reaload. like in the exemple
https://vue-multi-select.tuturu.io/#a_multiselect_array 
and it should work.

Manual reload is used to reload the init of vue-multi-select in the case u want to chase the model from outside of the component.

**Comment by greksazoo** [comment]
Hi,
I find little bug that belong to this issue.
When you run reloadInit on vuemultiselect in multi mode, getBtnLabel computed prop dont refresh itself.

I found this info about that after searching a little: 
https://github.com/vuejs/Discussion/issues/59

So when i change in the initValues() method this "this.valueSelected.length = 0;" to "this.valueSelected = [];", everything works fine. 

I like your component, good job and have a nice day!

**Comment by IneoO** [comment]
Thx, i will change that before the end of the week
