### ISSUE TITLE
v-model not updating widget

### ISSUE THREAD

**Issue by tbyte80** [IneoO/vue-multi-select#27]
I have the following code:
```xml
<multiselect  v-model="selectedTypes" :select-options="types" 
  :options="{multi: true, groups: false}">
 </multiselect>`
```
In one of my functions I call `this.selectedTypes.splice(0,this.selectedTypes.length);` to reset the array (deselect all) - it is part of resetting the whole form. However, the widget remains unchanged (selections are kept).

Please advise.

**Comment by IneoO** [comment]
Hi your issue is related to #23 

you have to use this example https://vue-multi-select.tuturu.io/#a_multiselect_array.

if u want to make a deselect you have to say to the component to reload.

you have to use reload `:reloadInit` and `@vueMultiSelectInited`

Cordialy

**Comment by tbyte80** [comment]
Yes, just found that issue. The reloadInit property did the trick but it's missing in the props list documentation :) .
Also found it a bit counterintuitive to solve it that way cuz v-model should be double data binding, right?

Anyway thanks a blast for responding so quick!

**Comment by IneoO** [comment]
Yeah sry, i will update props list
You are clearly right, when i find some times i will try to work on this.
