### ISSUE TITLE
Firefox Styling Issue

### ISSUE THREAD

**Issue by davidkassa** [IneoO/vue-multi-select#3]
There seem to be styling issues with Firefox. I'm using version 59.0.1

(BTW - this is a great component. Exactly what I was looking for).

![image](https://user-images.githubusercontent.com/814849/39505707-c8e2c824-4d99-11e8-8dbe-ced7b73478e5.png)

**Comment by IneoO** [comment]
Hi, ok, i haven't test on firefox, i will fix that as soon as possible.

**Comment by IneoO** [comment]
I forgot to update the doc with the num version, my bad, i will do it later. 

Thx
