### ISSUE TITLE
How to use html instead of plain text in options

### ISSUE THREAD

**Issue by arlad** [IneoO/vue-multi-select#39]
Hi,

is it possible to render html in options? I mean something like this:

`renderTemplate(option) { return '<i class="flag-icon flag-icon-' + option.label.toLowerCase() + '"></i> ' + option.label; }`

Right now it shows me plain text instead of country flag.

Thanks

**Comment by IneoO** [comment]
Hi, no atm this is not possible, i will try to implement this in one or two week.

**Comment by IneoO** [comment]
Hi, you can now do that. with renderTempalte function or labelHtml
