### ISSUE TITLE
how to use it in codepen.io?

### ISSUE THREAD

**Issue by JackZhouMine** [IneoO/vue-multi-select#41]
# How to use it in codepen?

hello,  I want to make some demos with **vue-multi-select**,but I dont know how to relize it. 
I can not find a url or cdn. 
Do you any idea ?

**Comment by IneoO** [comment]
Hi, you can use unpkg

https://codepen.io/IneoO/pen/drgBed

for css, [https://unpkg.com/vue-multi-select@3.12.1/dist/lib/vue-multi-select.min.css](https://unpkg.com/vue-multi-select@3.12.1/dist/lib/vue-multi-select.min.css)
for js [https://unpkg.com/vue-multi-select@3.12.1](https://unpkg.com/vue-multi-select@3.12.1)

**Comment by JackZhouMine** [comment]
thank you!
hi, bro , where i can find this url [https://unpkg.com/vue-multi-select@3.12.1](url) ? 
and I have a question that     How to change the direction in which the panel is expanded. if  the select options are to many, and page arrive at the bottom of window,i need to expand the panel in up. How to don that.

**Comment by IneoO** [comment]
I m not sure to understand, this url is provided for every package uploaded on npm.
it's a redirection on the index params on package.json (https://unpkg.com/vue-multi-select@3.12.1/dist/lib/vue-multi-select.min.js)

for the second point, that's actually not possible, i will make a feature this weekend to add this function

**Comment by IneoO** [comment]
Hi it's now possible with props position, you can specify where you want the options ('bottom-left' is default, you can set 'top-right', 'top-left', ...)
