### ISSUE TITLE
how to  disable the vue-muilti select selectpicker?? 

### ISSUE THREAD

**Issue by ashikapm** [IneoO/vue-multi-select#44]

**Comment by IneoO** [comment]
Hi, i made a feature to add this function. Just use props disabled on multiSelect

```
    <multi-select
      :disabled="isDisabled"
      v-model="values"
      :options="options"
      :filters="filters"
      :btnLabel="btnLabel"
      search
      historyButton
      :searchPlaceholder="Search"
      :selectOptions="data" />
```

**Comment by ashikapm** [comment]
I  already done this,but it doesn't work.Is there anything else to do..??

**Comment by IneoO** [comment]
Did you retry with 3.14.0 ? I made a pr yesterday to add this feature

you can see it working on this link https://codepen.io/IneoO/pen/WWwaYN

**Comment by ashikapm** [comment]
Thankyou so much....its working fine when i updated to 3.14.0.

**Comment by ashikapm** [comment]
I need to use this select-picker on edit,So how can I set saved values on it..?

**Comment by IneoO** [comment]
You want to init it with some values ? 

Depend of the structure of your values, but fill v-model should be enough

**Comment by ashikapm** [comment]
Thanksss
