### ISSUE TITLE
On change event fires twice

### ISSUE THREAD

**Issue by tigerstyles** [IneoO/vue-multi-select#46]
So as the title says.
This is my multi select.
```
<multi-select
     v-model="selectedArr"
     :selectOptions="cars"
     :btnLabel="btnLabel"
     @change="loadModels()"
     :eventName="'change'"
     class="custom-select-box"
 />
```
and then this is the loadModels() function which is being called on change.
```
loadModels() {
    this.loading = true;
    console.log('event fired');
    this.selected = this.selectedArr[0].id;
    store.dispatch(FETCH_MODELS, this.listConfig).then(() => this.loading = false);
}
```
Everytime I change the selected option I can see in the console, that `event fired` has been logged twice and also that there are two ajax calls being made via store dispatch. This latter one causes a lot of issues for me because of the following.
First there is a dispatch action which is called with the old value(ie. the value which was selected) and then there is a dispatch with the value which is selected now.

edit: was on v 3.12, updated to 3.14 now, but the behavior is the same

**Comment by IneoO** [comment]
Hi, sry for the pb,

just realeased 3.14.1 who fix the pb https://codesandbox.io/s/0k5x8wom0

**Comment by tigerstyles** [comment]
Works like a charm.
Thanks a lot for the speedy fix and also thanks for the amazing package, saved me a lot of time!
