### ISSUE TITLE
When v-model is update, all selectedOptions are pushed into v-model value.

### ISSUE THREAD

**Issue by ranbly** [IneoO/vue-multi-select#48]
I made new component using your library, thanks.
But I found a problem.

After the first multi selection (at least two),
when v-model’s value is update or change,
all values are pushed into Options(Param)

ex)
```
<MultiSelect
    v-model="values"
    :btnLabel="btnLabel"
    :options="options"
    :selectedOptions="selectOptions"
>
<template v-for="(item, index) in values">
   {{ item.content }} <button @click="values.splice(index, 1)">
</button>
</template>

</MultiSelect>

values : [
{
    content: 'a',
    id: '21'
}, 
{
    content: 'b',
    id: '31'
},
{
    content: 'c',
    id: '11'
},
{
    content: 'd',
    id: '17'
},
]
```

Every time I press the delete button, all values ​​in selectOptions are pushed.
This seems to be a bug. please check.

**Comment by ranbly** [comment]
https://codesandbox.io/embed/4w10j6z747

set data's 'name' to 'content'.
set options array data.
There is a problem.

``` 
renderTemplate(elem) { return `<u>${elem.content}</u>`; },
```

**Comment by IneoO** [comment]
So you have to set the `'labelValue'`, default is `labelName` -> `'name'` (since you didn't change labelName).
`labelValue` need to point an attributs who is unique. In your case maybe you can use `content`, or `id` 
this 'id' will be used to compare elements selected or not
like in your first exemple

https://codesandbox.io/s/l5mxm0m0ml

hope it solves your pb

**Comment by ranbly** [comment]
Thanks! 
I add 'labelValue' options.
But selectedOptions get all 'undefined'.

A key value of 'name' seems to be required.
`labelValue` does not seem to exactly match `name`.
This seems to be a bug. please check.

I've solved it by writing the additional code below.
```
computed: {
 values() {
            return this.values.map(value => {
                value['name'] = value.content;
            });
        },
}
```

Thanks.

**Comment by IneoO** [comment]
you can change name with `labelName` option

```
      options: {  
        renderTemplate(elem) { return `<u>${elem.content}</u>`; },
        multi: true,
        labelValue: 'content',
        labelName: 'content',
      },
```
