### ISSUE TITLE
How to fire close event manually

### ISSUE THREAD

**Issue by agiovinazzi** [IneoO/vue-multi-select#55]
Hello, I need to fire the close event manually (in particular, when keyboard Enter button is pushed). How can I manually calls this event from a method?

Thanks a lot in advance!

**Comment by IneoO** [comment]
Hi, i realised a codepen https://codepen.io/IneoO/pen/BevoVw?editors=1111.
It's a little tricky

You need to witch for enter button globaly and trigger `toggleCheckboxes` like it was a click event

```javascript
  mounted() {
    const self = this;
    window.addEventListener('keypress', (e) => {
      if (e.keyCode === 13 && self.$refs.multiSelect.isOpen) {
        const elem = this.$refs.multiSelect.$el.firstChild;
        self.$refs.multiSelect.toggleCheckboxes({ target: elem });
      }
    });
  },
```

**Comment by agiovinazzi** [comment]
Thanks, I'll try ASAP.
