### ISSUE TITLE
Get only value of selected item

### ISSUE THREAD

**Issue by bantawa04** [IneoO/vue-multi-select#58]
This plugin works like this
` <select name="name" multiple>`
 ` <option value="volvo">Volvo</option>`
  `<option value="saab">Saab</option>`
  `<option value="opel">Opel</option>`
  `<option value="audi">Audi</option>`
`</select> `
And stores and send data like the following while submitting the form
`[
  {
    "name": "volvo"
  },
  {
    "name": "opel"
  },
  {
    "name": "audi"
  }
]`

How do we make it work like this ? Store and send only values of selected items

`<select name="name" multiple>
 ` <option value="1">Volvo</option>`
  `<option value="2">Saab</option>`
 ` <option value="3">Opel</option>`
  `<option value="4">Audi</option>`
`</select>`

`[
  {
    "name": "1"
  },
  {
    "name": "3"
  },
  {
    "name": "4"
  }
]`

**Comment by IneoO** [comment]
if you pass object and only want values, I suggest you to use computed 
ex: https://codepen.io/IneoO/pen/BevoVw?editors=1111
