### ISSUE TITLE
Missing btnLabel v-html in v4.1 build

### ISSUE THREAD

**Issue by alantva** [IneoO/vue-multi-select#59]
Hi, I'm really enjoying your package.

And I'm trying to use btnLabel's v-html function, but it's not in v4.1's lib.

I needed to build manually inside my node_modules directory.

Would an upgrade be possible?

**Comment by IneoO** [comment]
Sry, i migrate on vue-serve short time ago and forgot that i have 1 command for build projet and 1 command for build lib. It's fine now with 4.1.1

**Comment by alantva** [comment]
@IneoO No problem, thank you.
