### ISSUE TITLE
Multiselect size

### ISSUE THREAD

**Issue by DragosPeta** [IneoO/vue-multi-select#60]
Gretings,

In our application the user can set the size of the bootstrap 4 inputs from the project: small, medium, large.

In order to do that on this component we need to apply the following classes on the button (that has btn-select class on it): btn btn-sm, btn btn-md, btn btn-lg. Also we need to change the font-size, padding and min-width from it. (these are set default by the following css: .select .inlineBlock[data-v-1604b90e]). 

Can you make a prop, or something that can give us access to customize/overwrite the button class? 

Thanks!

**Comment by IneoO** [comment]
Hi, does 4.2.0 resolve your pb ? you might need !important on some params

**Comment by DragosPeta** [comment]
Thanks a lot, that was fast.
It works but i had to redefine the bootstrap classes with new names in my style.css and put !important on all. Might not be the best solution but it works and it's ok for now.
Thanks again!
