### ISSUE TITLE
How to not allow un-select

### ISSUE THREAD

**Issue by songoo** [IneoO/vue-multi-select#62]
Hello , how can i disallow "un-selecting", so click on selected value again will not un-select it, I want to simulate classic select-box with single value where you cant un-select value, mainly for point that i have to have filled in value always.
Please advice :-) . 
```
            <vue-multi-select
                    v-model="adultsValue"
                    :options="options"
                    :selectOptions="adultsDrop"
            />
```

Tnx for great component!

**Comment by IneoO** [comment]
I, that's not possible for the moment, i will make a release with this feature before the end of the week.

**Comment by IneoO** [comment]
Hi, you can use disabledUnSelect props. If you want to apply a style (like cursor: disabled), you can use props options.cssSelected

**Comment by songoo** [comment]
Hello, thank you much!  You are THE Best :) , works SuperB.
Also tnx for pointing on cursor override style, was help-full :)
