### ISSUE TITLE
How to set the initial values to this component for multi-select?

### ISSUE THREAD

**Issue by smartstar3** [IneoO/vue-multi-select#65]
Hello ?
I am trying to use this component on Vue-cli project.
I wanna to set the initial values to this.
So I set them to the v-model, however it does not work.
Could you help me?
How can I solve this issue?
Thanks, 
Best regard.

**Comment by IneoO** [comment]
Hi can you send a codepen or try this ? 
https://codepen.io/IneoO/pen/BevoVw?editors=1111

Cordialy

**Comment by smartstar3** [comment]
It works well.
Thanks @IneoO .
