### ISSUE TITLE
Trigger Programmatically

### ISSUE THREAD

**Issue by ariefsn** [IneoO/vue-multi-select#66]
Hi,
how to trigger this programmatically??
open/close multiselect by other button click,,

**Comment by IneoO** [comment]
Hi,
I will make a feature to add this functionality before the end of the week

Cordialy

**Comment by ariefsn** [comment]
> Hi,
> I will make a feature to add this functionality before the end of the week
> 
> Cordialy

ok thanks will wait.
and how to make this width 100% that will auto adjust to fit parent's width?
