### ISSUE TITLE
Centering Text

### ISSUE THREAD

**Issue by fox880919** [iNeoO/vue-multi-select#69]
First of all thanks for your efforts on this component. 

I have a problem that on mobile devices the dropdown options are hard to keep in the center of the screen. Is there a way at least to to keep the text in the center rather that aligned on one side.

**Comment by iNeoO** [comment]
Hi,
i think the best way would be to overade .select.checkboxLayer with ::v-deep but atm (top/bottom/left/right) are in linteral in the code ... If i do a pr to pass style params as props would it be enough ?

**Comment by fox880919** [comment]
Sorry my late reply. I have to say I couldn't some of your abbreviations and words. But  I appreciate your reply.

I managed for the mobile device to work around it. First I had sometimes to disable search and history to minimize the size. And, I move it the corner so when it is open it doesn't leave the boundaries.

Keep up the good work on this.

**Comment by iNeoO** [comment]
Ok, sry for that.

Glad you succed to have what you wanted !

Thx !!
