### ISSUE TITLE
Problem with set default data in select

### ISSUE THREAD

**Issue by byinff** [iNeoO/vue-multi-select#70]
Hello,

I have been using your library and I have a problem with one thing. I tried to populate the select with data from ajax service and It works good but when I try to set default the checked options with the data in model "filters.types" it doesn't work.

There is my implementation for the plugin in my HTML
`
<VueMultiSelect
            v-model="filters.types"
            :btnLabel="btnLabel"
            :search="false"
            :historyButton="false"
            :selectOptions="data"
            :options="options"
            class="mb-3"
          >
          </VueMultiSelect>
`

There is the data property example of my component

`
data: [
          {
            title: "",
            elements: [],
          },
        ],
options: {
          multi: true,
          groups: true,
          labelList: "elements",
          groupName: "title",
        },
`

` 
activityService
        .types()
        .then((response) => {
          this.data[0].elements = response.data.types;
        })
        .catch(() => {});
`

The activity service returns the follow array :

`
["4x4","rapel"]
`

**Comment by byinff** [comment]
When I used the following link https://vue-multi-select.tuturu.io/#a_multiselect_array . I haven't any problem with this but with complex data values of array I have the problem

**Comment by byinff** [comment]
I have checked recently and I haven't the problem with complex data values of array but there is a problem with populate data dynamically and set into data property and use it in your plugin

**Comment by byinff** [comment]
The process is the following : 

I select the options, click in the refresh button, and the data stay set in the model but when I refresh the page and populate the prop v-model with the data there are not set in the plugin

**Comment by iNeoO** [comment]
Hi, i m not sure to understand your problem. I started a codepen, could you try to reproduce your problem ? 

https://codepen.io/IneoO/pen/BevoVw?editors=1111

**Comment by byinff** [comment]
Thanks for your answer. When I set the options in the plugin and click filter button in my app. I update the URL and when I refresh the app in the browser I get the filters and after that, I populate in the data model.

```
  const {
    types,
  } = setFilters(location);
```

setFilters is a function to parse query string URL and return an object with the key and value for each filter and after that, I set this value in my data model 

this.filters.types = types

But at the same time. I make an ajax call to get types and populate in the selected

**Comment by iNeoO** [comment]
So if i understand well, you set v-model, and with an asynchronous call set selectOptions ?

In vue-mutli-select you have a check at init to push selected values only if they exist in selectOptions. So since selectOptions are empty, v-model is cleared. Could you set v-model in the activityService ,then() ?

**Comment by byinff** [comment]
@iNeoO Yeaaaaahhhhh, sorry for the delay of my answer. Excellent I set the types in async of the function ajax and works correctly. Thanks a million
