### ISSUE TITLE
Multi select Button label without number

### ISSUE THREAD

**Issue by th-ink** [iNeoO/vue-multi-select#71]
Hey, I am trying to set the vue-multi-select button label to just display the name without the calculated select item amount, it can't seem to do that. 

`<vue-multi-select
                          v-model="venueValues"
                          :options="options"
                          :filters="venueFilters"
                          :btn-label="venueBtnLabel"
                          :select-options="venueData" />
`
and `venueBtnLabel: "venues"`

With this code I still see the calculated item value in the label.

**Comment by iNeoO** [comment]
Hi btnLabel is a function (with value as params),
https://codepen.io/IneoO/pen/BevoVw?editors=11

Did you try like this ?

**Comment by th-ink** [comment]
@iNeoO with this, I get the following error
```
vue.js:634 [Vue warn]: Invalid prop: type check failed for prop "btnLabel". Expected String with value "function testLabel(values) {
        return "A simple vue multi select";
      }", got Function 

found in

---> <MultiSelect>
       <Root>
```

**Comment by iNeoO** [comment]
Please update to 4.5.0

**Comment by th-ink** [comment]
Got ya', thanks. 
Is there a way to include version 4.5.0. from CDN within a `<script>` tag?

**Comment by iNeoO** [comment]
Yeah simply use plugin via CDN:
<script src="https://unpkg.com/vue-multi-select@4.5.0"></script>

Unpkg is provided by nodejs

**Comment by th-ink** [comment]
I did try doing it this way, but it seems that it might be the wrong file, as I get the following error:
```
vue-multi-select.common.js:1 Uncaught ReferenceError: module is not defined
    at vue-multi-select.common.js:1
```

**Comment by iNeoO** [comment]
Sry, it's this one, https://unpkg.com/vue-multi-select@4.5.0/dist/lib/vue-multi-select.umd.js

**Comment by th-ink** [comment]
That works, thank you very much!
