### ISSUE TITLE
array of objects as default values

### ISSUE THREAD

**Issue by Amir-Mohamadi** [iNeoO/vue-multi-select#72]
hello, when I set the default selected values as array of objects, it doesn't work and select all options! 
https://codepen.io/amirmoh/pen/XWKrYmQ

**Comment by iNeoO** [comment]
Hi,

in options, you have to specify the labelValue (if not same value than labelName)

```
      options: {
        multi: true,
        groups: true,
        labelValue: 'v',
        labelList: 'elements',
        groupName: 'title'
      },
```
