### ISSUE TITLE
Need OK button to Vue-Multi-select 

### ISSUE THREAD

**Issue by RajuADP** [IneoO/vue-multi-select#74]
Hi,
   How do i customize this vue-multi-select. I want to have the "OK" button in that and when click it, i'll grab the values selected from Values(v-model). AND i need this custom button within the tags with other properties like below

<vue-multi-select
                  :options="options"
                  :btnLabel="btnLabel"
                  :selectOptions="data"
                  search
                  historyButton
                  :filters="filters"
                  v-model="values"
               / >

To say it simply,  need OK button like historyButton

Please help me in this.

<img width="576" alt="multiselect" src="https://user-images.githubusercontent.com/26303427/104913531-bf64bb80-59b3-11eb-80ce-0400411c44c4.png">

**Comment by iNeoO** [comment]
I m not sure this component will fit what you want, v-model is actualized every time a value is clicked. You can still use the html/css to create your own component, and add the button ok under the panel.
