### ISSUE TITLE
How to programmically deselet base on index

### ISSUE THREAD

**Issue by olasunkanmi04** [IneoO/vue-multi-select#75]
Hi, please I am displaying my selected values in a tag format that should be deletable targeting the index and use splice.
But for some  reason, I can't just splice the index I want out, once I call the splice method on the index I want it starts checking all items in the options and keeps adding to the selected

**Comment by iNeoO** [comment]
Hi,
Could you provide a reproduce link ?

I think the best solution is to set again the variable in your v-model, this should trigger the reload of the init

**Comment by olasunkanmi04** [comment]
` remove(index) {
      console.log(index)
      this.formData.selectedSurvey.splice(index, 1)
    }`
    
  If you can look at the video to see the behaviour and also, that is the method I am calling on clicking of the x.
  
  Also,  how do I set again the variable in my v-model, I don't quite get that.
  
  Thank you and great package

**Comment by iNeoO** [comment]
try:
```
const selectedSurvey = [...this.formData.selectedSurvey]
 selectedSurvey.splice(index, 1);
 this.formData.selectedSurvey = selectedSurvey;
 ```

**Comment by olasunkanmi04** [comment]
Still the same result

**Comment by iNeoO** [comment]
Well i don't really know what is happening, i made a test with splice and all work fine. Can you show me the settings, props u are using

https://codepen.io/IneoO/pen/BevoVw

**Comment by olasunkanmi04** [comment]
```
`                   <vue-multi-select
                      ref="multiSelect"
                      v-model="formData.selectedSurvey"
                      :btn-label="selectSurveyLabel"
                      :filters="filters"
                      :options="options"
                      :search="true"
                      :select-options="allSurvey">
                      <template v-slot:option="{ option }">
                        <input :checked="option.selected" type="checkbox" />
                        <span>{{ option.title }}</span>
                      </template>
                    </vue-multi-select>`
```

There is nothing about splice in the codepen link you shared.

**Comment by iNeoO** [comment]
Sry, i didn't save the codepen, i updated it

https://codepen.io/IneoO/pen/BevoVw

the options and the type of allSurvey

Did you change `options.labelName` or `options.labelValue` ?

(`options.labelName` or `options.labelValue` could be 'title')

**Comment by olasunkanmi04** [comment]
No I didn't change options.labelName or options.labelValue. I didn't do anything related to that, am I to? and how?
allSurvey is an array of objects.

I think it has to do with array of objects.
I edited your codepen and tried to recreate my data and I got similar experience.
How am I to work with my array of objects?

**Comment by iNeoO** [comment]
Ok, you need to set `options.labelValue` with a unique key to identify your options (this key is used to compare ur options and detect selection/unselection) (it might be 'id' or maybe 'title')

I updated the codepein with obj https://codepen.io/IneoO/pen/BevoVw

**Comment by olasunkanmi04** [comment]
It works well now.
Thank you so much, I appreciate your time.

**Comment by iNeoO** [comment]
thx ! i close the issue
