### ISSUE TITLE
"Select All" filter only when text in search is entered  

### ISSUE THREAD

**Issue by sven-s** [IneoO/vue-multi-select#84]
Is there a way to enable/disable the "Select All" button, depending on the text entered in the search button?

I have a long list of multiple selections, and should not be possible to "Select All" without any filtering.

![image](https://user-images.githubusercontent.com/191672/155292998-e41a9076-cf38-48b4-8a91-84337ddd1342.png)

**Comment by iNeoO** [comment]
Hi, y, this is possible, but this is tricky (and pretty ugly)

You have to set a ref on vue-multi-select and watch it to set filters or not

```
  mounted() {
    this.$watch('$refs.multi.searchInput', (newValue) => {
      if (newValue) {
        this.filters = [{
          nameAll: 'Select all',
          nameNotAll: 'Deselect all',
          func() {
            return true;
          },
        }];
      } else {
        this.filters = [];
      }
    });
  },
  ```
