### ISSUE TITLE
Scroll style leaves space when the list is short

### ISSUE THREAD

**Issue by davidkassa** [IneoO/vue-multi-select#9]
When a scrollbar is not necessary the padding/spacing is not correct.

Bad:
![image](https://user-images.githubusercontent.com/814849/40074429-34637350-583f-11e8-82e5-e5eaf6dbf7f8.png)
Good:
![image](https://user-images.githubusercontent.com/814849/40074439-3bacb68a-583f-11e8-9f51-fab37063df8a.png)

**Comment by IneoO** [comment]
Huge thx to you for all these issues !
